### ISSUE TITLE
Error while generating dummy data.

### ISSUE THREAD

**Issue by Purvanshsingh** [open-risk/openNPL#1]
Error while running `loadfixtures.sh` bash script for generating dummy data.

![Screenshot from 2021-03-13 00-26-26](https://user-images.githubusercontent.com/49719371/110985955-132bc980-8393-11eb-922a-63b582f85aaf.png)

**Comment by open-risk** [comment]
Good catch. This should be fixed with the latest commit

**Comment by Purvanshsingh** [comment]
`loadfixtures.sh` script fixed with this [commit](https://github.com/open-risk/openNPL/commit/44188cae827e500a07f190c73220a3a358dd5c76).
