### ISSUE TITLE
Operational Error while generating Dummy data

### ISSUE THREAD

**Issue by Purvanshsingh** [open-risk/openNPL#2]
Operational error (no such table: npl_portfolio_portfolio ) in generating dummy data.

![Screenshot from 2021-03-16 19-55-35](https://user-images.githubusercontent.com/49719371/111326262-6b641380-8692-11eb-83e5-afd101c76fcd.png)

**Comment by open-risk** [comment]
@Purvanshsingh it looks like the database is not fully setup when you try to load the data. did you run django migrations before loading the data? See the full django steps / instructions [here](https://opennpl.readthedocs.io/en/latest/installation.html)

**Comment by Purvanshsingh** [comment]
This is the snapshot of the Database file with DB Browser

![Screenshot from 2021-03-16 20-26-29](https://user-images.githubusercontent.com/49719371/111330485-fd215000-8695-11eb-88c6-8f714c980d79.png)

**Comment by open-risk** [comment]
You are right the instructions need some adjustment :-) you should also run: 

  python3 manage.py makemigrations npl_portfolio
  python3 manage.py migrate

this will generate the npl_portfolio tables. 

you don't have to restart the installation, just issue these in your current setup and it should work

**Comment by Purvanshsingh** [comment]
@open-risk Thanks It worked,
closing this Issue and will create the Pull Request for changing `python3 manage.py makemigrations` to `python3 manage.py makemigrations npl_portfolio
`

**Comment by Tejashree-J** [comment]
Operational error while adding data
![exception](https://user-images.githubusercontent.com/81523913/113016598-45636680-919c-11eb-8142-24f791363006.png)

I have migrated all to the DB. This is my DB file screenshot

![DB browser](https://user-images.githubusercontent.com/81523913/113016649-514f2880-919c-11eb-923f-b603f1b5f077.png)

Please help to fix this. Thank you

**Comment by open-risk** [comment]
> Operational error while adding data
> ![exception](https://user-images.githubusercontent.com/81523913/113016598-45636680-919c-11eb-8142-24f791363006.png)
> 
> I have migrated all to the DB. This is my DB file screenshot
> 
> ![DB browser](https://user-images.githubusercontent.com/81523913/113016649-514f2880-919c-11eb-923f-b603f1b5f077.png)
> 
> Please help to fix this. Thank you
> 

You should try a pyshop or django forum as your project is not related to openNPL.
